CREATE TABLE photo (
photoId INT PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(255) NOT NULL,
content TEXT NOT NULL,
nickname VARCHAR(50) NOT NULL,
newfilename VARCHAR(255) NOT NULL,
filename VARCHAR(255) NOT NULL,
createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);